server:
  port: 8082
spring:
  profiles:
    active: dev
  jpa:
#    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: krishnendu@orsac.team
    password: Swati@801
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

dbschema: rdvts_oltp

oiipcra-app:
  messages:
    record-not-found: "Record Not Found"


