spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: Rdvt5@123
    url: jdbc:postgresql://10.150.0.126:5432/rdvts?currentSchema=rdvts_oltp,public
    username: app_rdvts


  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1


#AWS S3 Configuration
#aws:
#  access_key_id: AKIAWP75M2FMKB5J7DGW
#  secret_access_key: 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
#  s3:
#    region: ap-south-1
#    bucket: ofarisbucket

#accessImagePath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/"
#accessDocumentPath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/ContractDocument/"
#accessIssueDocumentPath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/IssueDocument/"
#accessAgencyImagePath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/AgencyImage/"
#saveAgencyImagePath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/AgencyImage/"
#accessWorkProgressImagePath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/WorkProgress/"
#accessGrievanceDocumentPath: "https://ofarisbucket.s3.ap-south-1.amazonaws.com/Grievance/"


#PDF IMAGE PATH
#octdmsLogoPath: "/usr/share/nginx/html/oiipcra_pdf_images/octdms-logo.png"
#odishaWhiteLogoPath: "/usr/share/nginx/html/oiipcra_pdf_images/odishaWhite.png"

